"use strict";
const assert=require('node:assert/strict');
const {sanitizedGateDiagnostic}=require('../../tools/deepdive-stage2/lib/candidate-gate');
const r=sanitizedGateDiagnostic({script:'gate.js',passed:false,output:'✗ L3 参照页哈希漂移：private values\nprivate audit answer should never be exposed\nTypeError: Cannot read properties of undefined (reading \'items\')'});
assert.equal(r.referenceHashDrift,true);assert.equal(r.exceptionType,'TypeError');assert.equal(r.propertyName,'items');
assert(!JSON.stringify(r).includes('private'));assert(!('output' in r));
const m=sanitizedGateDiagnostic({script:'gate.js',passed:false,output:"Error: Cannot find module 'C:\\private\\secrets\\missing.js'"});
assert.equal(m.missingModule,'missing.js');assert(!JSON.stringify(m).includes('secrets'));
assert.equal(sanitizedGateDiagnostic({script:'gate.js',passed:true,output:'success'}).referenceHashDrift,false);
console.log('✓ Sanitized gate diagnostics preserve categories and omit raw audit/process output');
const {createCandidateGate}=require('../../tools/deepdive-stage2/lib/candidate-gate');
const gate=createCandidateGate({});
const defects=gate.gateDefects({script:'l3.js',output:'L3 参照页哈希漂移：private hash and audit text'},'supervised-learning');
assert.equal(defects.length,1);
assert.equal(defects[0].type,'gate');
assert.equal(defects[0].code,'reference-hash-drift');
assert(!JSON.stringify(defects).includes('private'));
assert(!JSON.stringify(defects).includes('读者可见缺口'));
assert.equal(gate.gateDefects({script:'l3.js',output:'other failure'},'example')[0].type,'gate');
console.log('✓ Reference drift remains blocked without directing content rewrites');
const {previewReferenceBenchmark}=require('../../tools/deepdive-stage2/lib/candidate-gate');
const before={reference:{id:'reference',pageHash:'sha256:'+'a'.repeat(64)},minimumScore:90,dimensionFloors:{mechanism:8}};
const after=previewReferenceBenchmark(before,'reference','sha256:'+'b'.repeat(64));
assert.equal(before.reference.pageHash,'sha256:'+'a'.repeat(64));
assert.equal(after.reference.pageHash,'sha256:'+'b'.repeat(64));
after.reference.pageHash=before.reference.pageHash;
assert.deepEqual(after,before);
assert.throws(()=>previewReferenceBenchmark(before,'different','sha256:'+'b'.repeat(64)));
assert.throws(()=>previewReferenceBenchmark(before,'reference','bad-hash'));
console.log('✓ Reference preview preserves every standard and refuses other pages');
