"use strict";
const assert = require("node:assert/strict");
const crypto = require("node:crypto");
const { render } = require("../../tools/readiness/render-concept-preview");
const hash = value => "sha256:" + crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
const page = { title: "监督学习 <test>", subtitle: '输入 "与" 目标', html: '<section><h2>原有章节</h2><figure><svg></svg></figure><table><tr><td>原数据</td></tr></table><details><summary>自测</summary>原答案</details></section>' };
const snapshot = { schemaVersion: 1, pageId: "supervised-learning", sourceLocale: "zh-Hans", publicationAllowed: false, snapshotId: hash("snapshot"), sourcePageHash: hash("source"), sourceContentHash: hash(page), page };
const result = render(snapshot, "/AI-knowledge-map/");
assert.ok(result.includes(`<!-- source-body:start -->${page.html}<!-- source-body:end -->`), "Preserve original body byte for byte, including figures, tables and self-test.");
assert.ok(result.includes("监督学习 &lt;test&gt;"));
assert.ok(result.includes('href="/AI-knowledge-map/?lang=zh-Hans#/map/supervised-learning"'));
assert.ok(result.includes('href="/AI-knowledge-map/assets/style.css"'));
assert.ok(result.includes('name="robots" content="noindex, nofollow"'));
assert.ok(!/rel="canonical"|hreflang|<script/i.test(result), "Preview must not invent production or translation metadata.");
assert.throws(() => render({ ...snapshot, page: { ...page, html: "changed" } }), /hash mismatch/);
assert.throws(() => render({ ...snapshot, publicationAllowed: true }), /non-publishing/);
assert.throws(() => render({ ...snapshot, pageId: "../../secret" }), /Invalid page ID/);
assert.throws(() => render(snapshot, "//external.example/"), /Invalid site base/);
const active = { ...page, html: '<script>alert("no")</script>' };
assert.throws(() => render({ ...snapshot, page: active, sourceContentHash: hash(active) }), /Active content/);
console.log("PASS: preview content integrity, retained structures, escaped metadata, subpath links and non-publication boundaries.");
