"use strict";
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {writeArtifact,renderConcept,route}=require('../../tools/readiness/site-artifact');
const {verify}=require('../../tools/verify-website');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'website-fixture-'));
const siteUrl='https://example.org/map/';
const page={title:'测试与 <边界>',subtitle:'解释',html:'<section><h2>核心</h2><p>有完整正文 <span class="xref" data-goto="other">另一个概念</span></p><svg viewBox="0 0 560 100"><text>保留图表</text></svg></section>'};
const entry={id:'sample',locale:'zh',page,sourceHash:'fixture',eligible:true};
try {
  fs.writeFileSync(path.join(root,'index.html'),'<html><head><title data-i18n="app.title.graph">旧标题</title></head><body><header><span class="brand-name" id="brand-name">AI 知识地图</span></header><main id="stage"></main></body></html>');
  const mono=renderConcept(entry,[entry],siteUrl,true);
  assert(mono.includes('class="preview-brand" href="/map/?lang=zh-Hans"'), 'article brand returns to the fragment-free homepage');
  assert(mono.includes('/map/?lang=zh-Hans&amp;node=sample'), 'article node-location links retain their target');
  assert(mono.includes('<p>有完整正文'));assert(mono.includes('noindex'));assert(!mono.includes('hreflang="en"'));assert(!mono.includes('/en/concepts/sample/'));
  assert(mono.includes('/map/?lang=zh-Hans&amp;node=other'));assert(mono.includes('保留图表'));
  const en={...entry,locale:'en',page:{...page,title:'Test'}};
  en.englishVerified=true;en.translationEnvelope={schemaVersion:1,status:'machine-reviewed',payload:{pageId:'sample'}};
  const bilingual=renderConcept(entry,[entry,en],siteUrl,false);assert(bilingual.includes('hreflang="en"'));assert(bilingual.includes('/map/en/concepts/sample/'));
  assert.throws(()=>route('../bad','zh'));assert.throws(()=>route('sample','fr'));
  assert.throws(()=>writeArtifact({root,output:path.join(root,'blocked'),entries:[{...entry,eligible:false}],inventory:[],siteUrl,mode:'production'}));
  // Minimal fixture CSS/script assets used by the renderer, never real Stage 2 content.
  fs.mkdirSync(path.join(root,'assets','vendor'),{recursive:true});
  for(const name of ['style.css','concept-preview.css','reading.css','progress.css','reading.js','progress-model.js','progress-supabase.js','progress-runtime.js','progress-ui.js','site-search.js','release-navigation.js'])fs.writeFileSync(path.join(root,'assets',name),'');
  fs.writeFileSync(path.join(root,'assets','vendor','supabase-2.115.0.min.js'),'');
  fs.mkdirSync(path.join(root,'assets','social'),{recursive:true});fs.copyFileSync(path.resolve(__dirname,'../../assets/social/site-card.png'),path.join(root,'assets','social','site-card.png'));
  const output=path.join(root,'preview');
  writeArtifact({root,output,entries:[entry],inventory:[],siteUrl,mode:'preview',graph:{nodes:[{id:'sample',title:'示例'},{id:'other',title:'其他'}],edges:[{from:'sample',to:'other',type:'prerequisite'}]}});
  assert(fs.readFileSync(path.join(output,'search/index.html'),'utf8').includes('概念关系（→ 有向，— 无向）'));
  const directoryHtml=fs.readFileSync(path.join(output,'search/index.html'),'utf8');
  assert(directoryHtml.includes('href="/map/zh/concepts/sample/">示例</a>'));
  assert(!directoryHtml.includes('#/'), 'no released page may carry a fragment route');
  assert(directoryHtml.includes('href="/map/?lang=zh-Hans&amp;node=other"'), 'unpublished concepts must retain map fallback');
  assert(!directoryHtml.includes('/zh/concepts/other/'), 'never link to an unpublished article');
  assert.equal(verify(output).pages,1);assert.throws(()=>verify(output,true),/production/);
  fs.appendFileSync(path.join(output,'zh/concepts/sample/index.html'),'tampered');assert.throws(()=>verify(output),/changed/);
  const production=path.join(root,'production');writeArtifact({root,output:production,entries:[entry],inventory:[],siteUrl,mode:'production',graph:{nodes:[],edges:[]}});assert.equal(verify(production,true).status,'pass');
  // Hash-free view URLs: each interactive view ships a real, indexable directory
  // so GitHub Pages serves it without a rewrite and refresh keeps resolving.
  const libraryShell=fs.readFileSync(path.join(production,'library/index.html'),'utf8');
  const softwareShell=fs.readFileSync(path.join(production,'software/index.html'),'utf8');
  assert(libraryShell.includes('<base href="../">'),'view shells must resolve every asset against the site root');
  assert(softwareShell.includes('<base href="../">'));
  assert(libraryShell.includes('<link rel="canonical" href="https://example.org/map/library/">'));
  assert(softwareShell.includes('<link rel="canonical" href="https://example.org/map/software/">'));
  assert(!libraryShell.includes('#/')&&!softwareShell.includes('#/'),'view shells must not ship fragment routes');
  const releaseSitemap=fs.readFileSync(path.join(production,'sitemap.xml'),'utf8');
  assert(releaseSitemap.includes('<loc>https://example.org/map/library/</loc>'));
  assert(releaseSitemap.includes('<loc>https://example.org/map/software/</loc>'));
  const release=JSON.parse(fs.readFileSync(path.join(production,'release-manifest.json'),'utf8'));
  const monoPage=release.seoPages.find(p=>p.kind==='LearningResource');
  assert.deepEqual(monoPage.alternates,[],'missing translations must not be advertised');
  const head=fs.readFileSync(path.join(production,monoPage.file),'utf8').split('</head>')[0];
  assert.equal((head.match(/rel="canonical"/g)||[]).length,1);assert(head.includes('og:image'));assert(head.includes('BreadcrumbList'));
  assert(!head.includes('dateModified'),'build time must not become content modification time');assert(!head.includes('"author"'));
  const biOutput=path.join(root,'bilingual');writeArtifact({root,output:biOutput,entries:[entry,en],inventory:[],siteUrl,mode:'production',graph:{nodes:[],edges:[]}});
  assert.equal(verify(biOutput,true).status,'pass');
  const englishGuide=fs.readFileSync(path.join(biOutput,'en/index.html'),'utf8');
  assert(englishGuide.includes('<html lang="en">'));
  assert(englishGuide.includes('href="/map/en/concepts/sample/"'));
  assert(!englishGuide.includes('/en/concepts/llm/'), 'guide must not invent unpublished pages');
  assert(englishGuide.includes('hreflang="zh-Hans"'));
  assert(fs.readFileSync(path.join(biOutput,'search/index.html'),'utf8').includes('href="/map/en/">Learn AI'));
  assert(fs.readFileSync(path.join(biOutput,'en/concepts/sample/index.html'),'utf8').includes('href="https://example.org/map/en/">AI learning guide'));
  assert(!fs.existsSync(path.join(production,'en/index.html')), 'do not publish an empty language guide');
  const biRelease=JSON.parse(fs.readFileSync(path.join(biOutput,'release-manifest.json'),'utf8'));
  assert.equal(JSON.parse(fs.readFileSync(path.join(biOutput,'data/content-locales/en/deepdive/sample.json'),'utf8')).status,'machine-reviewed');
  const englishMeta=biRelease.seoPages.find(p=>p.locale==='en');assert.equal(englishMeta.alternates.length,2);
  const englishHtml=fs.readFileSync(path.join(biOutput,englishMeta.file),'utf8');assert(englishHtml.includes('<html lang="en">'));assert(englishHtml.includes('aria-label="Breadcrumb"'));
  const {verifySeo}=require('../../tools/readiness/verify-site-seo');
  const homePath=path.join(production,'index.html'),originalHome=fs.readFileSync(homePath,'utf8');
  assert.equal((originalHome.match(/<title\b[^>]*>/gi)||[]).length,1,'attribute-bearing legacy titles must be replaced');
  assert(originalHome.includes('<h1 class="brand-name"'));
  assert(originalHome.includes('data-release-search href="/map/search/"'), 'the initial homepage HTML must link to the directory');
  assert(/assets\/release-navigation\.js\?v=[a-f0-9]{16}/.test(originalHome), 'navigation scripts must refresh when their content changes');
  const duplicateHome=originalHome.replace('</head>','<title data-test="legacy">Duplicate</title></head>');
  fs.writeFileSync(homePath,duplicateHome);
  const duplicateManifest=JSON.parse(JSON.stringify(release));duplicateManifest.seoPages.find(p=>p.file==='index.html').contentHash=require('../../tools/readiness/site-seo').fingerprint(duplicateHome);
  assert.throws(()=>verifySeo(production,duplicateManifest),/title missing or duplicated/);
  fs.writeFileSync(homePath,originalHome);
  const robotsPath=path.join(production,'robots.txt'),originalRobots=fs.readFileSync(robotsPath,'utf8');
  fs.writeFileSync(robotsPath,originalRobots.replace('Allow: /','Disallow: /'));
  assert.throws(()=>verifySeo(production,release),/crawl policy/);
  fs.writeFileSync(robotsPath,originalRobots);
  const {robots}=require('../../tools/readiness/site-seo');
  const policy=robots(siteUrl,false,{searchCrawl:'allow',trainingCrawl:'disallow'});
  assert(policy.includes('OAI-SearchBot\nAllow: /'));assert(policy.includes('GPTBot\nDisallow: /'));
  assert.throws(()=>robots(siteUrl,false,{searchCrawl:'unknown',trainingCrawl:'allow'}),/policy/);
  const broken=JSON.parse(JSON.stringify(biRelease));broken.seoPages.find(p=>p.locale==='en').alternates=[];
  assert.throws(()=>verifySeo(biOutput,broken),/reciprocal|alternate/);
  fs.writeFileSync(path.join(biOutput,'sitemap.xml'),'<urlset><url><loc>https://example.org/map/en/concepts/not-published/</loc></url></urlset>');
  assert.throws(()=>verifySeo(biOutput,biRelease),/Sitemap/);
  fs.mkdirSync(path.join(root,'config'));
  fs.writeFileSync(path.join(root,'config','site-publishing.json'),JSON.stringify({siteUrl,searchCrawl:'allow',trainingCrawl:'allow',pageTitles:{'zh/concepts/sample/':'测试页面：概念与基础逻辑 | 测试品牌'}}));
  fs.writeFileSync(path.join(root,'config','brand.json'),JSON.stringify({nameZh:'AI 知识地图',nameEn:'AI Knowledge Map',maintainer:'LittleFishK',repository:'https://github.com/little-fishk/AI-knowledge-map',correctionsUrl:'https://github.com/little-fishk/AI-knowledge-map/issues',codeLicense:'MIT',contentLicense:'CC BY 4.0'}));
  fs.copyFileSync(path.resolve(__dirname,'../../LICENSE'),path.join(root,'LICENSE'));
  fs.mkdirSync(path.join(root,'config','site-verification'));
  const proofName='baidu_verify_codeva-fixture123.html', proof='0123456789abcdef0123456789abcdef';
  fs.writeFileSync(path.join(root,'config','site-verification',proofName),proof);
  const branded=path.join(root,'branded');writeArtifact({root,output:branded,entries:[entry],inventory:[],siteUrl,mode:'production',graph:{nodes:[],edges:[]}});
  assert.equal(verify(branded,true).status,'pass');
  assert.equal(fs.readFileSync(path.join(branded,proofName),'utf8'),proof);
  assert(!fs.readFileSync(path.join(branded,'sitemap.xml'),'utf8').includes(proofName));
  assert.throws(()=>require('../../tools/readiness/site-verification').validate('../invalid.html',Buffer.from(proof)),/Invalid/);
  assert.throws(()=>require('../../tools/readiness/site-verification').validate(proofName,Buffer.from('<script>bad</script>')),/Invalid/);
  const about=fs.readFileSync(path.join(branded,'about/index.html'),'utf8');
  assert(about.includes('LittleFishK'));assert(about.includes('AboutPage'));assert(about.includes('CC BY 4.0'));assert(about.includes('/issues'));assert(about.includes('第三方'));
  assert(!about.includes('mailto:'));assert(!about.includes('hreflang="en"'));
  assert(fs.readFileSync(path.join(branded,'index.html'),'utf8').includes('/map/about/'));
  const brandedConcept=fs.readFileSync(path.join(branded,'zh/concepts/sample/index.html'),'utf8');
  assert(brandedConcept.includes('<title>测试页面：概念与基础逻辑 | 测试品牌</title>'));
  assert(brandedConcept.includes('<h1 class="dd-h1">测试与 &lt;边界&gt;</h1>'),'search titles do not edit controller content');
  fs.writeFileSync(path.join(production,'.env'),'secret');assert.throws(()=>verify(production,true),/file set/);
  const publicEntry={...entry,eligible:false,publicAccess:true,reviewStatus:'pending-review'};
  const publicOutput=path.join(root,'open-reading');
  const publicArgs={root,entries:[publicEntry],inventory:[{id:'sample',eligible:false}],siteUrl,mode:'production',publicationPolicy:'open-reading',graph:{nodes:[],edges:[]}};
  writeArtifact({...publicArgs,output:publicOutput});
  assert.equal(verify(publicOutput,true).underReview,1);
  const publicManifest=JSON.parse(fs.readFileSync(path.join(publicOutput,'release-manifest.json'),'utf8'));
  assert.equal(publicManifest.pages[0].eligible,false,'public access never grants audit approval');
  assert.equal(publicManifest.pages[0].publicAccess,true);
  assert.equal(publicManifest.excluded.length,0);
  const publicHtml=fs.readFileSync(path.join(publicOutput,'zh/concepts/sample/index.html'),'utf8');
  assert(publicHtml.includes('data-review-status="pending-review"'));
  assert(publicHtml.includes('持续修订中'));
  assert(publicHtml.includes('<!-- source-body:start -->'+page.html.replace('<span class="xref" data-goto="other">另一个概念</span>','<a class="xref" data-goto="other" href="/map/?lang=zh-Hans&amp;node=other">另一个概念</a>')+'<!-- source-body:end -->'));
  assert.throws(()=>writeArtifact({...publicArgs,publicationPolicy:'approved-only',output:path.join(root,'strict-public')}),/Production requires/);
  assert.throws(()=>writeArtifact({...publicArgs,entries:[{...publicEntry,reviewStatus:'reviewed'}],output:path.join(root,'false-approval')}),/Production requires/);
  assert.throws(()=>writeArtifact({...publicArgs,entries:[{...publicEntry,locale:'en'}],output:path.join(root,'unapproved-english')}),/Production requires/);
  const reviewedEnglishOutput=path.join(root,'reviewed-english-public');
  writeArtifact({...publicArgs,entries:[publicEntry,{...en,eligible:false,reviewStatus:'pending-review',publicAccess:true}],output:reviewedEnglishOutput});
  assert.equal(verify(reviewedEnglishOutput,true).status,'pass');
  assert.equal(JSON.parse(fs.readFileSync(path.join(reviewedEnglishOutput,'release-manifest.json'),'utf8')).pages.find(p=>p.locale==='en').englishVerified,true);
  assert.throws(()=>writeArtifact({...publicArgs,publicationPolicy:'unknown',output:path.join(root,'unknown-policy')}),/publication policy/);
  const {render:notice}=require('../../assets/publication-notice');
  assert(notice('needs-revision').includes('本页部分内容有待修订'));
  assert(!notice('reviewed'));assert(!notice('<script>'));
  assert(notice('pending-review','en').includes('Continuously revised'));
  console.log('PASS: monolingual/bilingual URLs, full HTML, link fallback, preview/production gates, tamper and extra-file rejection');
} finally {if(path.dirname(root)!==path.resolve(os.tmpdir())||!path.basename(root).startsWith('website-fixture-'))throw Error('Unsafe fixture cleanup');fs.rmSync(root,{recursive:true,force:true});}
