"use strict";
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(process.argv[2]||'site-release');
const read=name=>fs.readFileSync(path.join(root,name),'utf8');
const manifest=JSON.parse(read('release-manifest.json'));
assert.equal(manifest.mode,'production');
assert.equal(manifest.publicationPolicy,'open-reading');
assert(manifest.pages.length>0);
assert.equal(manifest.pages.every(p=>['zh','en'].includes(p.locale)&&p.publicAccess===true),true);
assert.equal(new Set(manifest.pages.map(p=>`${p.locale}:${p.id}`)).size,manifest.pages.length);
assert.equal(manifest.excluded.length,0);
assert(manifest.pages.some(p=>p.id==='supervised-learning'&&p.eligible===true));
for(const p of manifest.pages.filter(p=>!p.eligible))assert(read(p.path).includes(`data-review-status="${p.reviewStatus}"`));
const home=read('index.html'),concept=read('zh/concepts/supervised-learning/index.html'),search=read('search/index.html'),notFound=read('404.html');
assert.equal(manifest.siteUrl,'https://ai-knowledge-map.com/');
assert.equal(read('CNAME').trim(),'ai-knowledge-map.com');
assert(home.includes('<link rel="canonical" href="https://ai-knowledge-map.com/">'));
assert(home.includes('application/ld+json'));assert(!home.includes('noindex'));
assert(concept.includes('<link rel="canonical" href="https://ai-knowledge-map.com/zh/concepts/supervised-learning/">'));
assert(concept.includes('hreflang="en"'));assert(!concept.includes('本地构建预览'));assert(!concept.includes('noindex'));
assert(search.includes('<link rel="canonical" href="https://ai-knowledge-map.com/search/">'));assert(!search.includes('noindex'));
assert(notFound.includes('noindex, nofollow'));assert(!notFound.includes('本地预览：'));
assert(fs.existsSync(path.join(root,'en','concepts')));
const sitemap=read('sitemap.xml');
for(const url of ['https://ai-knowledge-map.com/','https://ai-knowledge-map.com/search/','https://ai-knowledge-map.com/zh/concepts/supervised-learning/'])assert(sitemap.includes(`<loc>${url}</loc>`));
assert.equal((sitemap.match(/<url>/g)||[]).length,manifest.seoPages?manifest.seoPages.filter(p=>p.indexable).length:3);
if(manifest.seoPages?.some(p=>p.kind==='AboutPage')){
  const about=read('about/index.html');assert(about.includes('LittleFishK'));assert(about.includes('CC BY 4.0'));assert(about.includes('/licenses/MIT.txt'));assert(home.includes('href="/about/"'));
}
const navigation={};vm.runInNewContext(read('assets/concept-pages.js'),{window:navigation});
assert.deepEqual(Object.keys(navigation.AI_STATIC_CONCEPTS).sort(),Array.from(new Set(manifest.pages.map(p=>p.id))).sort());
assert.deepEqual(Object.keys(navigation.AI_STATIC_CONCEPTS['supervised-learning']),['zh-Hans','en']);
const searchIndex=JSON.parse(read('assets/site-search-index.json'));
assert.equal(searchIndex.filter(item=>item.kind==='中文理解页').length,manifest.pages.filter(p=>p.locale==='zh').length);
assert.equal(searchIndex.filter(item=>item.kind==='English reading').length,manifest.pages.filter(p=>p.locale==='en').length);
console.log(`PASS: ${manifest.pages.length} public reading pages, truthful review status, full bilingual navigation/search/sitemap, production and 404 policy`);
