"use strict";

const fs = require("fs");
const path = require("path");
const vm = require("vm");
const { pageContentHash } = require("../../deepdive/quality/deepdive-audit-contracts");
const {
  pageRegistrationSource,
  standaloneLayoutSource,
} = require("../../deepdive/runtime/standalone-page-source");
const { transformGraph } = require("../../video-ingest/node-application");
const { graphFingerprint } = require("../../video-ingest/shadow-review");
const {
  prepareGraphAuthorityWrite,
  renderGraphSource,
  writeGraphAuthority,
} = require("../../graph/shadow");
const { parseGraphSource } = require("../../graph/diagnostics");

function createPublication(options) {
  const {
    toolScripts,
    clone,
    sha256,
    atomicWrite,
    readJson,
    withinRoot,
    writeJson,
    loadSupplementQueue,
    runGate,
  } = options;

  function candidateRelativePath(id) {
    return `.stage2/results/${id}/candidate.json`;
  }

  function privateAuditRelativePath(id) {
    return `.stage2/results/${id}/audit.private.json`;
  }

  function provisionalPublicationRelativePath(id) {
    return `.stage2/results/${id}/provisional-publication.json`;
  }

  function editorialPublicationRelativePath(id) {
    return `.stage2/results/${id}/editorial-publication.json`;
  }

  function runtimeSource(id, page) {
    return "/* Generated by tools/build-deepdive-runtime.js. Do not edit. */\n"
      + "window.DEEPDIVE=window.DEEPDIVE||{};"
      + `window.DEEPDIVE[${JSON.stringify(id)}]=${JSON.stringify(page)};\n`;
  }

  function runtimeManifestSource(ids) {
    return "/* Generated by tools/build-deepdive-runtime.js. Do not edit. */\n"
      + `window.DEEPDIVE_RUNTIME=${JSON.stringify({
        base: "data/deepdive-runtime",
        ids: [...new Set(ids)].sort(),
      })};\n`;
  }

  function loadRuntimeIds(root) {
    const file = path.join(root, "data", "deepdive-runtime", "manifest.js");
    const context = { window: {} };
    vm.createContext(context);
    vm.runInContext(fs.readFileSync(file, "utf8"), context, { filename: file });
    return (context.window.DEEPDIVE_RUNTIME && context.window.DEEPDIVE_RUNTIME.ids) || [];
  }

  function applyCoreMembership(graphSource, id) {
    const marker = /((?:"core"|\bcore)\s*:\s*\[)/;
    const match = marker.exec(graphSource);
    if (!match) throw new Error("data/graph.js 缺少 core 数组");
    const start = graphSource.indexOf("[", match.index);
    let depth = 0;
    let quote = null;
    let escaped = false;
    for (let index = start; index < graphSource.length; index++) {
      const character = graphSource[index];
      if (quote) {
        if (escaped) escaped = false;
        else if (character === "\\") escaped = true;
        else if (character === quote) quote = null;
        continue;
      }
      if (character === "\"" || character === "'") {
        quote = character;
        continue;
      }
      if (character === "[") depth++;
      if (character === "]" && --depth === 0) {
        const body = graphSource.slice(start + 1, index);
        if (new RegExp(`["']${id.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}["']`).test(body)) return graphSource;
        const trimmed = graphSource.slice(0, index).replace(/\s+$/, "");
        const whitespace = graphSource.slice(trimmed.length, index);
        return `${trimmed},\n    ${JSON.stringify(id)}${whitespace}${graphSource.slice(index)}`;
      }
    }
    throw new Error("data/graph.js 的 core 数组未闭合");
  }

  function targetRecord(root, relativePath, afterContent) {
    const file = withinRoot(root, relativePath);
    const beforeExists = fs.existsSync(file);
    const beforeContent = beforeExists ? fs.readFileSync(file, "utf8") : "";
    return {
      relativePath,
      beforeExists,
      beforeContent,
      afterContent,
      beforeHash: sha256(beforeContent),
      afterHash: sha256(afterContent),
    };
  }

  function restoreTarget(root, target) {
    const file = withinRoot(root, target.relativePath);
    if (target.beforeExists) atomicWrite(file, target.beforeContent);
    else if (fs.existsSync(file)) fs.unlinkSync(file);
  }

  function publishedTargets(root, record, page, audit) {
    const id = record.id;
    const targets = [];
    if (record.integration) {
      let graphContent = fs.readFileSync(path.join(root, "data", "graph.js"), "utf8");
      const graphContext = { window: {} };
      vm.createContext(graphContext);
      vm.runInContext(graphContent, graphContext);
      if (
        record.integration.bindings
        && record.integration.bindings.graphHash
        && graphFingerprint(graphContext.window.GRAPH) !== record.integration.bindings.graphHash
      ) {
        throw new Error("正式地图已变化；新节点集成包需要重新计算学习路径与布局");
      }
      const manifest = { ...clone(record.integration), deepDive: page };
      graphContent = transformGraph(graphContent, manifest);
      if (manifest.core && manifest.core.requested) graphContent = applyCoreMembership(graphContent, id);
      graphContent = renderGraphSource(parseGraphSource(graphContent));
      targets.push(targetRecord(root, "data/graph.js", graphContent));
      const sourceDirectory = path.join(root, "data", "deepdive");
      const sourcePageCount = fs.readdirSync(sourceDirectory).filter(file => file.endsWith(".js")).length;
      if (!fs.existsSync(path.join(sourceDirectory, `${id}.js`))) {
        targets.push(targetRecord(
          root,
          "data/deepdive/.standalone-pages.json",
          standaloneLayoutSource(sourcePageCount + 1),
        ));
      }
    }
    targets.push(targetRecord(root, `data/deepdive/${id}.js`, pageRegistrationSource(id, page)));
    targets.push(targetRecord(
      root,
      `docs/deepdive-audits/${id}.json`,
      `${JSON.stringify(audit, null, 2)}\n`,
    ));
    targets.push(targetRecord(root, `data/deepdive-runtime/${id}.js`, runtimeSource(id, page)));
    targets.push(targetRecord(
      root,
      "data/deepdive-runtime/manifest.js",
      runtimeManifestSource([...loadRuntimeIds(root), id]),
    ));
    const supplementIds = new Set((record.origin && record.origin.ids) || []);
    if (supplementIds.size) {
      const queue = loadSupplementQueue(root);
      let changed = false;
      (queue.items || []).forEach(item => {
        if (supplementIds.has(item.id) && item.status === "pending") {
          item.status = "applied";
          item.appliedAt = new Date().toISOString();
          item.stage2PageHash = pageContentHash(page);
          changed = true;
        }
      });
      if (changed) {
        targets.push(targetRecord(
          root,
          "data/video-concept-supplements.json",
          `${JSON.stringify(queue, null, 2)}\n`,
        ));
      }
    }
    return targets;
  }

  function writePublicationTargets(root, record, targets, options = {}) {
    const writesGraph = targets.some(target => target.relativePath === "data/graph.js");
    const graphBaseline = writesGraph ? prepareGraphAuthorityWrite(root) : null;
    let currentShadowDigest = graphBaseline && graphBaseline.sourceDigest;
    let graphAuthority = null;
    const written = [];
    const changeMessage = options.changeMessage || "正式目标在暂行发布前变化";
    const failureMessage = options.failureMessage || "暂行发布后集成检查失败";
    const restoreMessage = options.restoreMessage || "已恢复本次暂行发布写入。";
    try {
      targets.forEach(target => {
        const file = withinRoot(root, target.relativePath);
        const current = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : "";
        if (sha256(current) !== target.beforeHash) {
          throw new Error(`${changeMessage}：${target.relativePath}`);
        }
        if (target.relativePath === "data/graph.js") {
          graphAuthority = writeGraphAuthority(
            root,
            parseGraphSource(target.afterContent),
            { expectedPreviousDigest: currentShadowDigest },
          );
          currentShadowDigest = graphAuthority.sourceDigest;
        } else {
          atomicWrite(file, target.afterContent);
        }
        written.push(target);
      });
      const validatorFactory = options.validators || (() => [
        runGate(root, root, toolScripts.graphValidator),
        runGate(root, root, toolScripts.deepDiveValidator),
        runGate(root, root, toolScripts.videoApplicationValidator),
      ]);
      const validators = validatorFactory();
      const failed = validators.find(result => !result.passed);
      if (failed) throw new Error(`${failureMessage}：${failed.script}\n${failed.output}`);
      return { targets, validators, graphAuthority };
    } catch (error) {
      written.reverse().forEach(target => {
        if (target.relativePath === "data/graph.js") {
          try {
            const restored = writeGraphAuthority(
              root,
              parseGraphSource(target.beforeContent),
              { expectedPreviousDigest: currentShadowDigest },
            );
            currentShadowDigest = restored.sourceDigest;
          } catch (authorityRestoreError) {
            error.message += `\n图分片权威恢复失败：${authorityRestoreError.message}`;
          }
        } else {
          restoreTarget(root, target);
        }
      });
      error.message += `\n${restoreMessage}`;
      throw error;
    }
  }

  function publishCandidate(root, record, page, audit) {
    const targets = publishedTargets(root, record, page, audit);
    const result = writePublicationTargets(root, record, targets, {
      changeMessage: "正式目标在发布前变化",
      failureMessage: "发布后集成检查失败",
      restoreMessage: "已恢复本次发布写入。",
      validators: () => [
        runGate(root, root, toolScripts.graphValidator),
        runGate(root, root, toolScripts.deepDiveValidator),
        runGate(root, root, toolScripts.deepDiveL3Audit, ["--require-benchmark", record.id]),
        runGate(root, root, toolScripts.videoApplicationValidator),
      ],
    });
    const receipt = {
      schemaVersion: 1,
      status: "published",
      pageId: record.id,
      pageHash: pageContentHash(page),
      auditHash: sha256(audit),
      publishedAt: new Date().toISOString(),
      targets: (result.targets || targets).map(target => ({
        relativePath: target.relativePath,
        beforeHash: target.beforeHash,
        afterHash: target.afterHash,
      })),
      validators: (result.validators || []).map(item => ({ script: item.script, passed: item.passed })),
      graphAuthority: result.graphAuthority && {
        status: result.graphAuthority.status,
        previousSourceDigest: result.graphAuthority.previousSourceDigest,
        sourceDigest: result.graphAuthority.sourceDigest,
        writeAuthority: result.graphAuthority.writeAuthority,
        deepEqualAfterReload: result.graphAuthority.deepEqualAfterReload,
      },
    };
    receipt.receiptHash = sha256(receipt);
    return receipt;
  }

  function publishEditorialHumanApprovedCandidate(root, record, page, audit, options = {}) {
    const targets = publishedTargets(root, record, page, audit);
    const result = writePublicationTargets(root, record, targets, {
      ...options,
      validators: options.validators || (() => [
        runGate(root, root, toolScripts.graphValidator),
        runGate(root, root, toolScripts.deepDiveValidator),
        runGate(root, root, toolScripts.videoApplicationValidator),
      ]),
    });
    const receipt = {
      schemaVersion: 1,
      status: "published-human-approved",
      pageId: record.id,
      pageHash: pageContentHash(page),
      auditHash: sha256(audit),
      publishedAt: new Date().toISOString(),
      machineBlockerCountAtApproval: (record.blockers || []).length,
      targets: (result.targets || targets).map(target => ({
        relativePath: target.relativePath,
        beforeHash: target.beforeHash,
        afterHash: target.afterHash,
      })),
      validators: (result.validators || []).map(item => ({ script: item.script, passed: item.passed })),
      graphAuthority: result.graphAuthority && {
        status: result.graphAuthority.status,
        previousSourceDigest: result.graphAuthority.previousSourceDigest,
        sourceDigest: result.graphAuthority.sourceDigest,
        writeAuthority: result.graphAuthority.writeAuthority,
        deepEqualAfterReload: result.graphAuthority.deepEqualAfterReload,
      },
    };
    receipt.receiptHash = sha256(receipt);
    return receipt;
  }

  function provisionalPageMetadata(record, page, blockers, reason, publishedAt) {
    return {
      schemaVersion: 1,
      status: "published-provisional",
      reviewStatus: "manual-review",
      label: "未通过审计 · 暂行版本",
      blockerCount: blockers.length,
      candidateHash: pageContentHash(page),
      publishedAt,
      reason: String(reason).trim().slice(0, 500),
    };
  }

  function provisionalPublishedTargets(root, record, page, audit) {
    if (record.integration) {
      throw new Error("新概念节点不能以不合格暂行版本发布；必须先通过正式门禁");
    }
    const targets = [
      targetRecord(root, `data/deepdive/${record.id}.js`, pageRegistrationSource(record.id, page)),
      targetRecord(root, `data/deepdive-runtime/${record.id}.js`, runtimeSource(record.id, page)),
      targetRecord(
        root,
        "data/deepdive-runtime/manifest.js",
        runtimeManifestSource([...loadRuntimeIds(root), record.id]),
      ),
    ];
    if (audit) {
      targets.push(targetRecord(
        root,
        `docs/deepdive-audits/${record.id}.json`,
        `${JSON.stringify(audit, null, 2)}\n`,
      ));
    }
    return targets;
  }

  function editorialDraftMetadata(record, page, reviewStatus, blockerCount = 0) {
    const labels = {
      "audit-pending": "待审草稿",
      "repair-pending": "机器审查未通过 · 等待返修",
      "verification-pending": "返修完成 · 等待定向复核",
      "human-revision-pending": "人工退回 · 等待修改",
      "human-review-pending": "机器审查通过 · 等待人工审查",
      "human-review-blocked": "机器审查未通过 · 等待人工审查",
    };
    return {
      schemaVersion: 1,
      status: "published-editorial-draft",
      reviewStatus,
      label: labels[reviewStatus] || "待审草稿",
      blockerCount,
      candidateHash: pageContentHash(page),
      publishedAt: record.publication && record.publication.publishedAt || new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      reason: record.publication && record.publication.reason || "新版正文待审",
    };
  }

  function refreshEditorialDraftPublication(root, record, page, reviewStatus, blockerCount, options = {}) {
    const publication = editorialDraftMetadata(record, page, reviewStatus, blockerCount);
    const draftPage = { ...clone(page), publication };
    const targets = provisionalPublishedTargets(root, record, draftPage, null)
      .filter(target => !target.relativePath.endsWith("manifest.js"));
    const writer = options.publishEditorialDraft || ((targetRoot, targetRecordValue, targetValues) =>
      writePublicationTargets(targetRoot, targetRecordValue, targetValues, options));
    const result = writer(root, record, targets, publication) || { targets };
    record.publication = publication;

    if (record.editorialReceipt) {
      const receiptPath = withinRoot(root, record.editorialReceipt);
      if (fs.existsSync(receiptPath)) {
        const receipt = readJson(receiptPath);
        for (const target of result.targets || targets) {
          const saved = (receipt.targets || []).find(item => item.relativePath === target.relativePath);
          if (saved) {
            saved.afterContent = target.afterContent;
            saved.afterHash = target.afterHash;
          }
        }
        receipt.pageHash = pageContentHash(page);
        receipt.lastDraftStatus = reviewStatus;
        receipt.receiptHash = sha256({ ...receipt, receiptHash: undefined });
        writeJson(receiptPath, receipt);
      }
    }
    return publication;
  }

  return {
    applyCoreMembership,
    candidateRelativePath,
    editorialPublicationRelativePath,
    loadRuntimeIds,
    pageRegistrationSource,
    privateAuditRelativePath,
    provisionalPageMetadata,
    provisionalPublicationRelativePath,
    provisionalPublishedTargets,
    publishCandidate,
    publishEditorialHumanApprovedCandidate,
    refreshEditorialDraftPublication,
    restoreTarget,
    runtimeManifestSource,
    runtimeSource,
    targetRecord,
    writePublicationTargets,
  };
}

module.exports = { createPublication };
