'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const model = require('../../assets/onboarding-model');
const context = {window: {}};
vm.runInNewContext(fs.readFileSync(path.join(__dirname, '../../assets/onboarding-content.js'), 'utf8'), context);
const lessons = context.window.AI_ONBOARDING_LESSONS;
const count = lessons.length;
const english = context.window.AI_ONBOARDING_LESSONS_EN;
assert.equal(english.length, count);
english.forEach((lesson, index) => {
  const source = lessons[index];
  assert.equal(lesson.id, source.id);
  assert.equal(lesson.sections.length, source.sections.length);
  lesson.sections.forEach((section, i) => {
    assert.deepEqual(section[1].match(/<[^>]+>/g), source.sections[i][1].match(/<[^>]+>/g), 'translated sections preserve markup');
  });
  assert.equal(lesson.figure?.cards.length, source.figure?.cards.length);
  assert.deepEqual(Array.from(lesson.sources, row => row[1]), Array.from(source.sources, row => row[1]));
  assert.doesNotMatch(JSON.stringify(lesson), /[\u3400-\u9fff]/u);
});
assert.equal(count, 6);
assert.equal(new Set(lessons.map(x => x.id)).size, count);
assert.equal(lessons[0].figure, undefined, 'the rewritten first lesson has no inline figure');
assert.ok(lessons[0].thesis.startsWith('AI是一类让计算机从信息中寻找规律'));
const generationLesson = lessons.find((lesson) => lesson.id === 'understand-generation');
assert.ok(generationLesson);
assert.equal(generationLesson.sections[0][0], '一个水果的例子');
assert.match(generationLesson.sections[0][1], /苹果和香蕉的照片/);
assert.match(generationLesson.sections[1][1], /当前话题中的回答/);
assert.doesNotMatch(generationLesson.sections[0][1], /橡胶/);
const promptLesson = lessons.find((lesson) => lesson.id === 'say-what-you-need');
assert.ok(promptLesson);
assert.equal(promptLesson.sections[2][0], '清晰、严谨，继续追问');
assert.match(promptLesson.sections[1][1], /3个步骤，每步不超过两句话/);
assert.match(promptLesson.sections[1][1], /重新训练模型不是一回事/);
assert.doesNotMatch(promptLesson.sections.map((section) => section[1]).join(''), /追问的越多.*越好/);
const checkingLesson = lessons.find((lesson) => lesson.id === 'check-answers');
assert.ok(checkingLesson);
assert.equal(checkingLesson.title, '我能相信AI的答案吗？');
assert.match(checkingLesson.sections[2][1], /知识库和任务说明能帮助限定范围/);
assert.match(checkingLesson.sections[2][1], /不能保证内容正确/);
assert.doesNotMatch(checkingLesson.sections[2][1], /AI会引以为戒/);
const exploringLesson = lessons.find((lesson) => lesson.id === 'start-exploring');
assert.ok(exploringLesson);
assert.equal(exploringLesson.thesis, '想清楚任务，再选合适的工具；遇到想弄懂的问题，就去知识地图继续探索。');
assert.equal(exploringLesson.sections[2][0], '这张AI知识地图怎么用？');
assert.match(exploringLesson.sections[0][1], /普通程序或固定流程有时更可靠/);
assert.match(exploringLesson.sections[1][1], /让不同应用交换信息的接口/);
assert.match(exploringLesson.sections[1][1], /不含私人信息的小材料试一试/);
assert.doesNotMatch(exploringLesson.sections.map((section) => section[1]).join(''), /可以避免之后整个任务的错误/);
for (const lesson of lessons) {
  assert.ok(lesson.sections.length >= 3 && lesson.sources.length);
  if (lesson.figure) assert.ok(lesson.figure.cards.length >= 3);
  assert.ok(lesson.sections.every(([title, html]) => title && html.includes('<p>')));
}
let state = model.normalize(null, count);
assert.equal(model.unlocked(state, count), false);
assert.deepEqual(model.visit(state, 4, count), state, 'a locked stop cannot be visited');
state = model.advance(state, count);
assert.equal(state.read, 1);
assert.equal(state.cursor, 1);
state = model.visit(state, 0, count);
state = model.advance(state, count);
assert.equal(state.read, 1, 'rereading does not double-count progress');
state = model.normalize(JSON.parse(JSON.stringify(state)), count);
assert.equal(state.cursor, 1, 'resume at the next unread stop');
for (let i = 1; i < count; i++) state = model.advance(state, count);
assert.equal(model.unlocked(state, count), true);
assert.equal(state.read, 6);
assert.equal(state.cursor, 5);
const skipped = {...model.normalize(null, count), skipped: true};
assert.equal(model.unlocked(skipped, count), true);
assert.equal(skipped.read, 0, 'skipping is not evidence of reading');
assert.equal(model.merge(state, {version: 1, read: 1}, count).read, 6, 'another tab cannot erase progress');
assert.equal(model.normalize({version: 1, read: 1, cursor: 5}, count).cursor, 1);
assert.equal(model.normalize({version: 9, read: 6, skipped: true}, count).read, 0);
console.log('PASS onboarding content and progression model');
