'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const http = require('node:http');
const os = require('node:os');
const path = require('node:path');
const {pathToFileURL} = require('node:url');
const root = path.resolve(__dirname, '../..');
let playwright;
try { playwright = require('playwright'); }
catch (_) { playwright = require(require.resolve('playwright', {paths: [path.join(os.homedir(), '.cache/codex-runtimes/codex-primary-runtime/dependencies/node')]})); }
const {chromium} = playwright;
const executablePath = [process.env.DEEP_DIVE_BROWSER_PATH, chromium.executablePath(), 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', 'C:/Program Files/Google/Chrome/Application/chrome.exe'].find(p => p && fs.existsSync(p));
const key = 'ai-knowledge-map.onboarding.v1';
const fixtureManifest = 'window.DEEPDIVE_RUNTIME={base:"data/deepdive-runtime",ids:["supervised-learning"],revision:"onboarding-test"};';
const fixturePage = 'window.DEEPDIVE=window.DEEPDIVE||{};window.DEEPDIVE["supervised-learning"]={title:"Navigation fixture",html:"<p>Navigation fixture</p>"};';
// Only public UI/data are served; Stage 2 bodies are replaced with a synthetic navigation fixture.
const server = http.createServer((request, response) => {
  const relative = new URL(request.url, 'http://localhost').pathname.replace(/^\/+/, '') || 'index.html';
  if (relative === 'data/deepdive-runtime/manifest.js') return response.writeHead(200, {'Content-Type':'text/javascript'}).end(fixtureManifest);
  if (relative === 'data/deepdive-runtime/supervised-learning.js') return response.writeHead(200, {'Content-Type':'text/javascript'}).end(fixturePage);
  const allowed = relative === 'index.html' || relative.startsWith('assets/') || relative === 'data/graph.js' || relative.startsWith('data/locales/') || relative === 'data/content-locales/en/graph.js' || /^data\/(software|tutorials[^/]*|library[^/]*)\.js$/.test(relative);
  const file = path.resolve(root, relative);
  if (!allowed || !file.startsWith(root + path.sep)) return response.writeHead(404).end();
  fs.readFile(file, (error, body) => {
    if (error) return response.writeHead(404).end();
    const type = file.endsWith('.js') ? 'text/javascript' : file.endsWith('.css') ? 'text/css' : file.endsWith('.svg') ? 'image/svg+xml' : 'text/html';
    response.writeHead(200, {'Content-Type': type, 'Cache-Control': 'no-store'}).end(body);
  });
});
async function fixtureRoutes(context) {
  await context.route('**/data/deepdive-runtime/manifest.js', route => route.fulfill({contentType:'text/javascript',body:fixtureManifest}));
  await context.route('**/data/deepdive-runtime/supervised-learning.js', route => route.fulfill({contentType:'text/javascript',body:fixturePage}));
  await context.route('https://**/*', route => route.abort());
}
async function main() {
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const base = `http://127.0.0.1:${server.address().port}/index.html`;
  const browser = await chromium.launch({executablePath, headless: true});
  const errors = [];
  const shots = path.join(root, '.tmp', 'onboarding-qa');
  fs.mkdirSync(shots, {recursive:true});
  try {
    const context = await browser.newContext({viewport:{width:1440,height:1000}});
    await fixtureRoutes(context);
    const page = await context.newPage();
    page.on('pageerror', e => errors.push(e.message));
    await page.goto(base);
    await page.locator('#onboarding').waitFor();
    await page.waitForFunction(()=>!!window.AI_SETTINGS);
    for (const [source,target] of [['#btn-onboarding','[data-skip]'],['#btn-settings','[data-settings]']]) {
      await page.waitForFunction(([a,b])=>JSON.stringify(document.querySelector(a).getBoundingClientRect())===JSON.stringify(document.querySelector(b).getBoundingClientRect()),[source,target]);
      assert.deepEqual(await page.locator(source).boundingBox(),await page.locator(target).boundingBox(),'tutorial toolbar matches map toolbar');
    }
    await page.locator('[data-settings]').click();
    assert.equal(await page.locator('#settings-overlay').isVisible(),true);
    assert.equal(await page.locator('#topbar [data-progress-account-button]').count(),0);
    await page.locator('#settings-account').getByRole('button',{name:'账户',exact:true}).click();
    assert.equal(await page.locator('.progress-account-dialog').isVisible(),true);
    await page.keyboard.press('Escape');
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#settings-overlay').isVisible(),false);
    assert.equal(await page.locator('.onboarding-route').count(), 1);
    assert.equal(await page.locator('.onboarding-reader').count(), 0);
    assert.equal(await page.locator('[data-visit]').count(), 1);
    assert.equal((await page.locator('#onboarding').innerText()).replace(/\s+/g,' ').trim(), '返回地图 认识AI');
    assert.deepEqual(await page.locator('.onboarding-face').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('src'))),['assets/node-art/foundations.png?v=2']);
    await page.waitForFunction(()=>[...document.querySelectorAll('.onboarding-dot img')].every(img=>img.complete&&img.naturalWidth>0));
    assert.equal(await page.locator('.onboarding-dot').first().evaluate(n=>{const r=n.getBoundingClientRect();return r.x+r.width/2-innerWidth/2;}),0);
    assert.equal(await page.locator('.onboarding-dot').first().evaluate(n=>{const r=n.getBoundingClientRect();return r.y+r.height/2-innerHeight/2;}),0);
    assert.equal((await page.locator('.onboarding-dot').first().boundingBox()).width,72);
    const firstRing=page.locator('.onboarding-ring-spin').first();
    assert.equal(await firstRing.evaluate(n=>n.getAnimations()[0].effect.getTiming().duration),48000);
    const angle=await firstRing.evaluate(n=>getComputedStyle(n).transform);
    await page.waitForFunction(previous=>getComputedStyle(document.querySelector('.onboarding-ring-spin')).transform!==previous,angle);
    await page.locator('.onboarding-dot').first().hover();
    await page.waitForFunction(()=>document.querySelector('.onboarding-ring-spin').getAnimations()[0].playbackRate===16);
    assert.equal(await page.locator('.onboarding-dot').first().evaluate(n=>n.classList.contains('is-hovered')),true);
    await page.mouse.move(0,0);
    await page.waitForFunction(()=>document.querySelector('.onboarding-ring-spin').getAnimations()[0].playbackRate===1);
    await page.locator('.onboarding-dot').last().hover();
    await page.waitForFunction(()=>[...document.querySelectorAll('.onboarding-ring-spin')].at(-1).getAnimations()[0].playbackRate===16);
    await page.mouse.move(0,0);
    await page.emulateMedia({reducedMotion:'reduce'});
    await page.waitForFunction(()=>document.querySelector('.onboarding-ring-spin').getAnimations()[0].playState==='paused');
    await page.emulateMedia({reducedMotion:'no-preference'});
    assert.equal(await page.getByText(/已读过 \d+ \/ \d+ 站/).count(), 0);
    await page.locator('[data-skip]').focus();
    await page.keyboard.press('Shift+Tab');
    assert.equal(await page.locator('[data-visit="0"]').evaluate(node=>node===document.activeElement),true);
    await page.keyboard.press('Tab');
    assert.equal(await page.locator('[data-skip]').evaluate(node=>node===document.activeElement),true);
    assert.equal(await page.evaluate(() => document.querySelector('#app').inert && !window.__cy), true);
    await page.screenshot({path:path.join(shots, 'desktop-first.png')});
    await page.locator('[data-visit="0"]').click();
    assert.equal(await page.locator('.onboarding-route').count(), 0);
    await page.locator('[data-map]').click();
    assert.equal(await page.locator('[data-visit]').count(), 1);
    await page.locator('[data-visit="0"]').click();
    assert.equal(await page.getByRole('button',{name:'已读',exact:true}).count(),1);
    assert.equal(await page.getByRole('button',{name:/下一站/}).count(),0);
    await page.locator('[data-read]').click();
    assert.equal(await page.locator('.onboarding-route').count(),1);
    assert.equal(await page.locator('[data-visit]').count(),2);
    await page.reload();
    assert.equal(await page.locator('.onboarding-reader').count(), 0);
    assert.equal(await page.locator('[data-visit]').count(), 2);
    const positions=await page.locator('.onboarding-dot').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().y));
    assert(positions[1]<positions[0],'newly unlocked node appears above the first');
    await page.locator('[data-visit="1"]').click();
    await page.getByRole('heading', {name:'AI为什么能回答、写作和画画？',exact:true}).waitFor();
    await page.locator('[data-prev]').click();
    await page.locator('[data-read]').click();
    assert.equal(await page.evaluate(k => JSON.parse(localStorage.getItem(k)).read, key), 1);
    for (let i=1;i<6;i++) {
      assert.equal(await page.locator('[data-visit]').count(),i+1);
      await page.locator(`[data-visit="${i}"]`).click();
      if (i===3) {
        assert.equal(await page.locator('#onboarding-lesson-title').textContent(), '我能相信AI的答案吗？');
        await page.screenshot({path:path.join(shots, 'desktop-answer.png')});
      }
      assert.equal(await page.locator('.onboarding-route').count(), 0);
      await page.locator('[data-read]').click();
      assert.equal(await page.locator('.onboarding-route').count(),1);
      assert.equal(await page.locator('.onboarding-reader').count(),0);
    }
    assert.equal(await page.locator('[data-visit]').count(),6);
    assert.equal(await page.locator('#onboarding').isVisible(),true);
    await page.locator('[data-skip]').click();
    await page.waitForFunction(() => !!window.__cy);
    assert.equal(await page.locator('#onboarding').isVisible(), false);
    assert.equal(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)).read, key),6);
    await page.reload();
    await page.waitForFunction(() => !!window.__cy);
    assert.equal(await page.locator('#onboarding').isVisible(), false);
    await page.locator('#btn-onboarding').click();
    assert.equal(await page.locator('[data-visit]:disabled').count(), 0);
    assert.equal(await page.locator('[data-visit]').count(), 6);
    assert.deepEqual(await page.locator('.onboarding-face').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('src'))),['foundations','building','coding','generation','safety','frontier'].map(name=>`assets/node-art/${name}.png?v=2`));
    await page.screenshot({path:path.join(shots,'desktop-unlocked.png')});
    await page.locator('[data-visit="0"]').click();
    assert.equal(await page.locator('#onboarding-lesson-title').textContent(),'AI能帮我做什么？');
    await page.locator('[data-skip]').click();
    assert.equal(await page.evaluate(() => document.querySelector('#app').inert),false);
    await page.waitForFunction(()=>document.querySelector('#node-ring-motion')&&__cy.nodes('.motion-art').length);
    const coalesced=await page.evaluate(async()=>{
      const ctx=document.querySelector('#node-ring-motion').getContext('2d'),original=ctx.clearRect;
      let paints=0;ctx.clearRect=function(...args){paints++;return original.apply(this,args);};
      for(let i=0;i<30;i++)__cy.emit('render');
      const immediate=paints;
      await new Promise(resolve=>requestAnimationFrame(resolve));
      ctx.clearRect=original;
      return {immediate,paints};
    });
    assert.equal(coalesced.immediate,0,'map render bursts do not paint rings synchronously');
    assert.equal(coalesced.paints,1,'render burst is coalesced into one animation-frame paint');
    assert(await page.locator('#btn-reset').evaluate(n=>n.getBoundingClientRect().x<document.querySelector('#btn-onboarding').getBoundingClientRect().x));
    assert.equal(await page.locator('#focus-on, #focus-hops').count(),0);
    await page.locator('[data-scope="all"]').click();
    await page.waitForTimeout(700);
    const viewport=()=>page.evaluate(()=>({box:(()=>{const r=document.querySelector('#cy').getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height};})(),pan:__cy.pan(),zoom:__cy.zoom(),node:__cy.nodes().first().renderedPosition()}));
    const before=await viewport();
    await page.locator('#controls-toggle').click();
    await page.waitForTimeout(250);
    assert.deepEqual(await viewport(),before,'collapsing sidebar keeps the map stationary');
    await page.locator('#controls-toggle').click();
    await page.waitForTimeout(250);
    assert.deepEqual(await viewport(),before,'expanding sidebar keeps the map stationary');
    await page.evaluate(()=>{__cy.zoom(1.45);__cy.center(__cy.getElementById('llm'));});
    await page.waitForFunction(()=>__cy.nodes('.viewport-occluded').length>0);
    assert.equal(await page.locator('#map-side-curtains').evaluate(n=>getComputedStyle(n).pointerEvents),'none');
    const concealed=await page.evaluate(()=>__cy.nodes('.viewport-occluded').not('.hidden').first().id());
    const unchangedPosition=await page.evaluate(id=>({...__cy.getElementById(id).position()}),concealed);
    await page.evaluate(id=>__cy.center(__cy.getElementById(id)),concealed);
    await page.waitForFunction(id=>!__cy.getElementById(id).hasClass('viewport-occluded'),concealed);
    assert.deepEqual(await page.evaluate(id=>({...__cy.getElementById(id).position()}),concealed),unchangedPosition,'panning reveals occluded nodes without moving their graph coordinates');
    await page.evaluate(()=>__cy.center(__cy.getElementById('llm')));
    await page.waitForTimeout(200);
    await page.screenshot({path:path.join(shots,'desktop-side-curtains.png')});
    await page.evaluate(()=>{location.hash='#/map/supervised-learning';});
    await page.locator('#detail-toggle:not(.hidden)').waitFor();
    await page.waitForTimeout(700);
    await page.waitForTimeout(1200);
    const introduction=await page.locator('#detail-body').innerHTML();
    const relationship=()=>page.evaluate(()=>({selected:__cy.nodes('.sel').map(n=>n.id()),nodes:__cy.nodes().map(n=>({id:n.id(),position:n.position(),classes:n.classes().filter(c=>c!=='viewport-occluded')})),hash:location.hash,zoom:__cy.zoom()}));
    const selected=await relationship();
    await page.locator('#detail-toggle').click();
    assert.equal(await page.locator('#detail-toggle').getAttribute('aria-expanded'),'false');
    assert.equal(await page.locator('#detail-body').isVisible(),false);
    assert.deepEqual(await relationship(),selected,'collapsing introduction preserves the relationship graph');
    await page.locator('#detail-toggle').click();
    assert.equal(await page.locator('#detail-body').isVisible(),true);
    assert.equal(await page.locator('#detail-body').innerHTML(),introduction);
    assert.deepEqual(await relationship(),selected);
    await page.screenshot({path:path.join(shots,'desktop-introduction-toggle.png')});
    await page.evaluate(()=>__cy.emit('tap'));
    assert.equal(await page.locator('#detail-toggle').isVisible(),false);
    assert.equal(await page.evaluate(()=>__cy.nodes('.sel').length),0);
    await page.locator('[data-mode="software"]').click();
    await page.locator('#software-view .sw-card').first().waitFor();
    await context.close();

    const mobile = await browser.newContext({viewport:{width:390,height:844}});
    await fixtureRoutes(mobile);
    const small = await mobile.newPage();
    small.on('pageerror', e => errors.push(e.message));
    await small.goto(base + '?lang=en#/map/supervised-learning');
    await small.locator('#onboarding').waitFor();
    await small.waitForFunction(()=>!!window.AI_SETTINGS);
    await small.waitForFunction(()=>document.querySelector('#btn-onboarding').getBoundingClientRect().width===document.querySelector('[data-skip]').getBoundingClientRect().width);
    assert.deepEqual(await small.locator('#btn-onboarding').boundingBox(),await small.locator('[data-skip]').boundingBox());
    await small.locator('[data-settings]').click();
    await small.locator('#settings-close').click();
    assert.equal(await small.locator('[data-visit]').count(),1);
    assert.equal(await small.locator('.onboarding-dot').first().evaluate(n=>{const r=n.getBoundingClientRect();return r.x+r.width/2-innerWidth/2;}),0);
    await small.screenshot({path:path.join(shots,'mobile-first.png')});
    assert.equal(await small.evaluate(()=>document.querySelector('#onboarding').scrollWidth <= innerWidth),true);
    await small.locator('[data-visit="0"]').click();
    await small.locator('[data-read]').click();
    await small.locator('[data-visit="1"]').click();
    await small.locator('[data-read]').click();
    await small.locator('[data-visit="2"]').click();
    await small.locator('.dd-fig').scrollIntoViewIfNeeded();
    await small.screenshot({path:path.join(shots,'mobile-figure.png')});
    await small.locator('[data-skip]').click();
    await small.waitForFunction(()=>window.__cy?.nodes('.sel').first().id()==='supervised-learning');
    await small.locator('#detail-toggle').click();
    assert.equal(await small.locator('#detail-body').isVisible(),false);
    assert.equal(await small.evaluate(()=>__cy.nodes('.sel').first().id()),'supervised-learning');
    await small.locator('#detail-toggle').click();
    assert.equal(await small.locator('#detail-body').isVisible(),true);
    await small.screenshot({path:path.join(shots,'mobile-map.png')});
    await small.locator('#btn-onboarding').click();
    await small.locator('[data-visit="2"]').click();
    await small.getByRole('heading',{name:'怎样让AI听明白我的意思？',exact:true}).waitFor();
    await small.locator('[data-skip]').click();
    assert.equal(await small.locator('html').getAttribute('lang'),'en');
    assert.equal(await small.locator('#btn-settings').isVisible(),true);
    assert.equal(await small.evaluate(k=>JSON.parse(localStorage.getItem(k)).read, key),2);
    await small.reload();
    await small.waitForFunction(()=>!!window.__cy);
    assert.equal(await small.locator('#onboarding').isVisible(),false);
    await mobile.close();

    const broken = await browser.newContext();
    await fixtureRoutes(broken);
    await broken.addInitScript(() => { Object.defineProperty(Storage.prototype,'setItem',{value(){throw new Error('Storage blocked');}}); });
    const failed = await broken.newPage();
    // Unrelated legacy progress UI may report its own storage error; the onboarding must remain usable.
    await failed.goto(base);
    await failed.locator('[data-visit="0"]').click();
    await failed.locator('.onboarding-storage').waitFor();
    await failed.locator('[data-read]').click();
    await failed.locator('[data-visit="1"]').click();
    await failed.getByRole('heading',{name:'AI为什么能回答、写作和画画？',exact:true}).waitFor();
    await failed.locator('[data-skip]').click();
    await failed.waitForFunction(()=>!!window.__cy);
    await broken.close();

    const denied = await browser.newContext();
    await fixtureRoutes(denied);
    await denied.addInitScript(() => { Object.defineProperty(window,'localStorage',{get(){throw new DOMException('Storage blocked','SecurityError');}}); });
    const unavailable = await denied.newPage();
    unavailable.on('pageerror',e=>errors.push(e.message));
    await unavailable.goto(base);
    await unavailable.locator('[data-visit="0"]').click();
    await unavailable.locator('.onboarding-storage').waitFor();
    await unavailable.locator('[data-skip]').click();
    await unavailable.waitForFunction(()=>!!window.__cy);
    await denied.close();

    const corrupt = await browser.newContext();
    await fixtureRoutes(corrupt);
    await corrupt.addInitScript(k=>localStorage.setItem(k,'{broken'),key);
    const reset = await corrupt.newPage();
    reset.on('pageerror',e=>errors.push(e.message));
    await reset.goto(base+'#/concept/supervised-learning');
    await reset.locator('[data-visit="0"]').click();
    await reset.getByRole('heading',{name:'AI能帮我做什么？',exact:true}).waitFor();
    await reset.locator('[data-skip]').click();
    await reset.locator('#deepdive:not(.hidden)').waitFor();
    assert.match(await reset.locator('#dd-article').textContent(),/Navigation fixture/);
    await corrupt.close();

    const offline = await browser.newContext();
    await fixtureRoutes(offline);
    const file = await offline.newPage();
    file.on('pageerror',e=>errors.push(e.message));
    await file.goto(pathToFileURL(path.join(root,'index.html')).href);
    await file.locator('#onboarding').waitFor();
    await file.locator('[data-visit="0"]').click();
    await file.locator('[data-read]').click();
    await file.reload();
    await file.locator('[data-visit="1"]').click();
    await file.getByRole('heading',{name:'AI为什么能回答、写作和画画？',exact:true}).waitFor();
    await file.locator('[data-skip]').click();
    await file.waitForFunction(()=>!!window.__cy);
    await offline.close();
    assert.deepEqual(errors,[]);
    console.log('PASS onboarding browser: progress, replay, skip, deep links, mobile, storage failure, corrupt storage, file://');
    console.log(`Screenshots: ${shots}`);
  } finally { await browser.close(); }
}
main().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>server.close());
