"use strict";
// Explicit, reviewable queries; discovery has no authority to publish content.
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..');
const coverage=JSON.parse(fs.readFileSync(path.join(root,'proposals/arxiv-catalog/coverage.json'))).coverage;
const overrides={
 'attention':['self attention','attention mechanism','neural attention'],
 'transformer':['transformer architecture','transformer model','attention transformer'],
 'residual-connection':['residual network','residual connection','skip connection'],
 'scaling-law':['neural scaling law','scaling laws','compute optimal'],
 'llm':['large language model','language modeling','foundation model'],
 'tokenization':['tokenization','tokenisation','byte pair encoding','sentencepiece'],
 'embedding':['word embedding','sentence embedding','text embedding','word representation'],
 'context-window':['long context','context window','context length extension'],
 'sampling-params':['nucleus sampling','decoding strategies','language model sampling','text degeneration'],
 'fine-tuning':['fine tuning','finetuning','instruction tuning','supervised fine tuning'],
 'neural-network':['neural network','deep learning'],
 'backprop':['backpropagation','back propagation','automatic differentiation'],
 'cnn':['convolutional neural network','convolutional network'],
 'rnn':['recurrent neural network','long short term memory','gated recurrent unit'],
 'self-supervised-learning':['self supervised learning','self supervision','masked autoencoder'],
 'reinforcement-learning':['reinforcement learning','policy optimization','q learning'],
 'regularization':['neural regularization','dropout','weight decay'],
 'clustering':['clustering','k means','DBSCAN'],
 'dimensionality-reduction':['dimensionality reduction','principal component analysis','t SNE','UMAP'],
 'pretraining':['pretraining','pre training'],
 'rag':['retrieval augmented generation','retrieval augmented language'],
 'vector-db':['vector database','approximate nearest neighbor','similarity search','HNSW'],
 'chunking':['document chunking','text chunking','chunking for retrieval','semantic chunking'],
 'retrieval':['neural retrieval','dense retrieval','semantic search','sparse retrieval'],
 'reranking':['reranking','re ranking','cross encoder'],
 'constrained-decoding':['constrained decoding','grammar constrained','structured generation'],
 'prompt-caching':['prompt caching','prefix caching','KV cache reuse','radix attention'],
 'structured-output':['structured output','JSON generation','schema constrained'],
 'cot':['chain of thought','chain of thoughts','step by step reasoning'],
 'agent':['language model agent','LLM agent','AI agent','agentic'],
 'tool-calling':['tool calling','function calling','tool augmented language','tool use'],
 'mcp':['model context protocol'],
 'mcp-architecture':['model context protocol','MCP server','MCP client'],
 'agent-loop':['agent loop','agentic workflow','reasoning and acting'],
 'agent-memory':['agent memory','memory for agents','long term memory'],
 'diffusion':['diffusion model','denoising diffusion','score based generative'],
 'evaluation':['LLM evaluation','LLM as a judge','language model evaluation','agent evaluation'],
 'advanced-rag':['retrieval augmented generation','query rewriting','GraphRAG','Self RAG'],
 'inference-optimization':['LLM inference','KV cache','FlashAttention','speculative decoding'],
 'quantization':['neural network quantization','model quantization','language model quantization','GPTQ','AWQ'],
 'deployment':['LLM serving','language model serving','model deployment','inference serving'],
 'rlhf':['reinforcement learning from human feedback','preference optimization','preference alignment'],
 'red-teaming':['red teaming language','AI red teaming','red teaming AI'],
 'interpretability':['model interpretability','mechanistic interpretability','explainable AI','feature attribution'],
 'moe':['mixture of experts','sparse expert'],
 'distillation':['knowledge distillation','model distillation','policy distillation'],
 'model-families':['language model technical report','Llama','Gemini','DeepSeek','Qwen','Claude','GPT'],
 'hallucination':['language model hallucination','hallucinations','factuality','TruthfulQA'],
 'reward-hacking':['reward hacking','specification gaming','reward overoptimization'],
 'alignment':['AI alignment','language model alignment','alignment of language models'],
 'reasoning-models':['reasoning language model','reasoning models','large reasoning model'],
 'agent-frameworks':['agent framework','multi agent framework','AutoGen','LangGraph','CrewAI'],
 'multi-agent':['multi agent','multiagent'],
 'guardrails':['guardrails','LLM safety filter','language model safety filter'],
 'model-selection':['language model selection','LLM selection','cost quality tradeoff'],
 'react':['synergizing reasoning and acting','ReAct agent'],
 'data-poisoning':['data poisoning','backdoor attack','training poisoning'],
 'bias-fairness':['algorithmic fairness','model bias','language model bias','fairness in machine learning'],
 'privacy':['differential privacy','privacy in machine learning','membership inference','training data extraction'],
 'governance':['AI governance','AI regulation','EU AI Act','AI risk management'],
 'streaming':['streaming language model','streaming inference','streaming generation'],
 'logprobs':['language model confidence','token probability','token log probability'],
 'system-prompt':['system prompt','role prompting','instruction hierarchy'],
 'observability':['LLM observability','agent observability','LLM tracing','agent tracing'],
 'code-execution':['code execution language model','code interpreter','agent sandbox'],
 'computer-use':['computer use agent','GUI agent','web agent','OSWorld','WebArena'],
 'reflection':['self reflection language model','self critique','Reflexion','self refinement'],
 'knowledge-graph':['knowledge graph','GraphRAG'],
 'clip':['contrastive language image','CLIP model','vision language contrastive'],
 'vae':['variational autoencoder','auto encoding variational'],
 'audio-generation':['audio generation','music generation','text to audio'],
 'world-models':['world model','neural radiance field','3D generation','gaussian splatting'],
 'content-detection':['AI generated text detection','language model watermark','AI watermark','synthetic media detection'],
 'code-generation':['code generation','program synthesis','AI coding'],
 'planning':['language model planning','task planning','task decomposition','agent planning'],
 'coding-tools':['coding agent','coding assistant','AI programming','software engineering agent'],
 'workflow-orchestration':['agent orchestration','LLM workflow','agentic workflow'],
 'constitutional-ai':['constitutional AI','reinforcement learning from AI feedback','RLAIF'],
 'prefilling':['LLM prefill','prompt prefill','response prefilling','assistant prefill'],
 'citations':['attributed generation','citation generation','citation faithfulness','grounded language generation'],
 'context-compaction':['context compaction','context compression','prompt compression'],
 'agent-skills':['agent skill','skill library','lifelong learning agent','skill discovery'],
 'batch-norm':['batch normalization','BatchNorm'],
 'loss-function':['loss function','objective function'],
 'information-theory':['information bottleneck','cross entropy','Kullback Leibler','minimum description length'],
 'kernel-methods':['kernel method','support vector machine','kernel trick'],
 'normalization':['layer normalization','RMSNorm','root mean square normalization'],
 'optimizer-schedule':['Adam optimizer','AdamW','learning rate schedule','adaptive optimization'],
 'peft-lora':['parameter efficient fine tuning','low rank adaptation','LoRA','QLoRA'],
 'model-evaluation':['language model benchmark','language model evaluation','LLM benchmark'],
 'model-routing':['LLM routing','model routing','language model cascade'],
 'data-drift-monitoring':['data drift','concept drift','distribution shift detection','model monitoring'],
 'agent-identity-access':['agent authorization','agent identity','agent access control','AI agent permissions'],
 'flow-matching':['flow matching','rectified flow'],
 'training-data-governance':['training data curation','data provenance','dataset curation','training data governance'],
 'uncertainty-calibration':['uncertainty calibration','confidence calibration','selective prediction','conformal prediction'],
 'test-time-compute':['test time compute','inference time scaling','test time scaling','process reward model'],
 'state-space-models':['selective state space','state space sequence','Mamba'],
 'gan':['generative adversarial network'],
 'speech':['speech recognition','speech synthesis','text to speech'],
 'positional-encoding':['positional encoding','position embedding','rotary position'],
 'controllable-generation':['controllable generation','ControlNet','conditional generation'],
 'human-in-the-loop':['human in the loop','human agent collaboration'],
};
const cutoff='202609231633';
const domain='(cat:cs.* OR cat:stat.* OR cat:eess.* OR cat:math.OC OR ti:"machine learning" OR abs:"machine learning" OR ti:"deep learning" OR abs:"deep learning" OR ti:"neural network" OR abs:"neural network" OR ti:"language model" OR abs:"language model" OR ti:"artificial intelligence" OR abs:"artificial intelligence")';
const topic=coverage.map(n=>{
 const terms=overrides[n.nodeId]||[...new Set(n.searchTerms.filter(s=>/^[a-zA-Z][a-zA-Z -]+$/.test(s)&&s.length>4).map(s=>s.toLowerCase()))];
 if(!terms.length)throw Error('No terms '+n.nodeId);
 let query='('+terms.flatMap(t=>['ti:"'+t+'"','abs:"'+t+'"']).join(' OR ')+') AND '+domain;
 if(n.nodeId==='transformer')query='('+query+' OR ((ti:transformer OR abs:transformer) AND (ti:attention OR abs:attention) AND '+domain+'))';
 return {id:'node-'+n.nodeId,nodeIds:[n.nodeId],kind:'topic-history-and-frontier',terms,query,from:'199101010000',to:cutoff,fields:['title','abstract'],categories:'cs.*, stat.*, eess.*, math.OC，或题名/摘要明确涉及机器学习、深度学习、神经网络、语言模型、AI',completionRule:'All API-reported matching IDs harvested, with date splitting and page receipts; not a content-approval decision.'};
});
const cats=['cs.AI','cs.CL','cs.LG','stat.ML','cs.CV','cs.SD','eess.AS','cs.RO','cs.SE','cs.CR','cs.IR','cs.HC','cs.MA','cs.DC'];
const category=cats.map(cat=>({id:'category-'+cat,kind:'category-frontier',nodeIds:[],query:'cat:'+cat,from:'202509230000',to:cutoff,categories:[cat],completionRule:'All API-reported matching IDs in the last-year category window; no importance implied.'}));
const plan={schemaVersion:1,revision:2,runDirectory:'.local/arxiv-discovery/20260923-r2',createdAt:'2026-09-23',cutoffUTC:'2026-09-23T16:33:00Z',topicCount:topic.length,frontierCategories:cats,description:'130节点的标题/摘要主题检索（1991至截止时刻，采用计算机/统计/信号分类或明确AI关键词的领域限定）+14相关分类近一年检索；全部分页遍历。跨分类、版本按基础ID去重。元数据命中不代表入库。',queries:[...topic,...category]};
const dest=path.join(root,'proposals/arxiv-catalog/systematic-search-plan.json');
fs.writeFileSync(dest,JSON.stringify(plan,null,2)+'\n');
console.log(dest,plan.queries.length);
